export interface NuonVariable {
  name: string;
  template: string;
  description: string;
  category: string;
}

export const NUON_VARIABLES: NuonVariable[] = [
  // Install variables
  { name: "Public Domain", template: "{{.nuon.install.public_domain}}", description: "The public domain for this install", category: "Install" },
  { name: "Install ID", template: "{{.nuon.install.id}}", description: "Unique identifier for the install", category: "Install" },
  { name: "Install Name", template: "{{.nuon.install.name}}", description: "Name of the install", category: "Install" },
  { name: "Region", template: "{{.nuon.install.region}}", description: "Cloud region for the install", category: "Install" },

  // Install Inputs
  { name: "Custom Input", template: '{{.nuon.install.inputs.your_input_name}}', description: "Custom input defined in your app config", category: "Inputs" },

  // Infrastructure outputs
  { name: "Cluster Endpoint", template: "{{.nuon.install.infra.cluster_endpoint}}", description: "Kubernetes cluster API endpoint", category: "Infrastructure" },
  { name: "Cluster CA", template: "{{.nuon.install.infra.cluster_ca_certificate}}", description: "Cluster CA certificate", category: "Infrastructure" },
  { name: "Database Host", template: "{{.nuon.install.infra.database_host}}", description: "Database hostname", category: "Infrastructure" },
  { name: "Database Name", template: "{{.nuon.install.infra.database_name}}", description: "Database name", category: "Infrastructure" },
  { name: "Database User", template: "{{.nuon.install.infra.database_user}}", description: "Database username", category: "Infrastructure" },
  { name: "Database Password", template: "{{.nuon.install.infra.database_password}}", description: "Database password", category: "Infrastructure" },

  // App variables
  { name: "App ID", template: "{{.nuon.app.id}}", description: "The app identifier", category: "App" },
  { name: "App Name", template: "{{.nuon.app.name}}", description: "The app name", category: "App" },
];

export function generateNuonConfig(
  repoUrl: string,
  chartPath: string,
  chartName: string,
  valuesYaml: string
): string {
  const escapedValues = valuesYaml.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

  return `# Nuon Component Configuration
# Generated by byocify.com

[helm_chart]
name      = "${chartName}"
repo      = "${repoUrl}"
chart_dir = "${chartPath}"

[helm_chart.values]
inline = """
${valuesYaml}
"""
`;
}
